spring:
  profiles:
    active: dev
#    数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
  #    MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.hellooooo.jobsubmission.pojo
