file:
  basepath: D:\\Temp\\
  submitURL: https://hellooooo.top/job/
spring:
  #  配置邮箱
  mail:
    host: smtp.qq.com
    username: 431862144@qq.com
    password: xxx
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true